In [1]:
# import necessary libraries 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import functools
import random
import math
from operator import itemgetter

In [ ]:
#Define L2 Norm
def L2Norm(vec1, vec2):
   
    return math.sqrt((vec1-vec2)@(vec1-vec2))

L2Norm(np.array([1,2]), np.array([0,0]))

In [3]:
otherPoints = np.array([[1,2], [2,3], [0,1], [0,0]])
print(otherPoints)
point = np.array([0,0])
output = []
for row in otherPoints:
    output.append(L2Norm(row, point))

print(output)
output 
length = np.arange(len(output))



indexed_output = [output, length.tolist()]

indexed_output = zip(*indexed_output)

output = sorted(indexed_output, key=itemgetter(0))
dist = []









[[1 2]
 [2 3]
 [0 1]
 [0 0]]
[2.23606797749979, 3.605551275463989, 1.0, 0.0]


In [9]:
#Getting nearest K neighbors : iteratively defined
#The method did not work; it worked fine when it comes to getting neighbors but it failed to return the predicted value i.e. y hat


def getNeighborIndices(point, k, otherPoints):
    output = []
    for row in otherPoints:
        output.append(L2Norm(row, point))
    
    length = np.arange(len(output))
    output = [output, length.tolist()]
  
    output.sort(key=itemgetter(0))
   
    dist = []
    
    for i in range(1, k+1):
        dist.append((int)(output[0][-i]))
    return np.array(dist)

def getNeighbors(point, k, otherPoints, othersWResp):
    Neighbors = []
    j = getNeighborIndices(point, k, otherPoints)
    for i in range(0, k):
        
        
        Neighbors.append(othersWResp[(j[i])])
    return Neighbors
    
    
    

    

In [10]:
#Testing the function
print(getNeighborIndices(point, 2, otherPoints))
print(np.array(getNeighbors(point, 2, otherPoints, otherPoints)))
trainSet = [[2, 2, 2], [4, 4, 4 ]]
testInstance = [5, 5, 5]
k = 1
neighbors = getNeighbors(np.array(testInstance), 1, np.array(trainSet), np.array(trainSet))
print(np.array(neighbors))

[3 2]
[[0 0]
 [0 1]]
[[4 4 4]]


In [35]:
test = np.genfromtxt('DS1_test.csv', delimiter = ',')
valid = np.genfromtxt('DS1_valid.csv', delimiter = ',')
train = np.genfromtxt('DS1_train.csv', delimiter = ',')
print(np.shape(test))
print(np.shape(valid))
print(np.shape(train))
    

(800, 21)
(800, 21)
(2400, 21)


In [40]:
#After 3 days with some help, I was able to find a more optimal implementation
def class_map(x,k): #Implementation of K-NN
    nn = []
    for i,row in enumerate(train):
        point = np.array(row[:-1])
        dif = x-point
        dist = L2Norm(dif, 0) # l2
        
        if len(nn)<k:
            nn.append([dist,i]) #save the L2norm and the index of the point
        else:
            nn.sort(key=lambda x: x[0]) #sort our nearest neighbours based on dist
            if dist<nn[k-1][0]: #if we are closer than the farthest neighbour we replace it with the current val
                del nn[-1]
                nn.append([dist,i])
       
    mean = 0
    for n in nn:
        i = n[1] # row in train data
        val = train[i][-1] #grab 0,1 val of row
        mean += val
    mean /= k
    

    if mean<.5:
        return 0
    else:
        return 1

In [45]:
# test accuracy, precision, recall, and F-measure to get the ideal k
tp = 0
tn = 0
fp = 0
fn = 0
total = 0
k=2

for k in range(1,10):
    for row in valid:
        total +=1
        x = np.array(row[:-1])
        true_val = row[-1]

        decision = class_map(x,k)

        if decision == 0:
            if true_val == 0: #specificity
                tn+=1
            else: #Error Type II
                fn+=1
        else:
            if true_val == 0: #Error Type I
                fp+=1
            else: #sensitivity
                tp+=1



    acc = (tn+tp)/total
    prec = tp/(tp+fp) 
    rec = tp/(tp+fn)
    f = 2*prec*rec/(prec+rec)

    print(f"k: {k}")
    print(f"Accuracy would be: {acc}")
    print(f"Precision obtained: {prec}")
    print(f"Recall is: {rec}")
    print(f"F Measure observed: {f}")
    print('\n')

k: 1
Accuracy would be: 0.5325
Precision obtained: 0.5321782178217822
Recall is: 0.5375
F Measure observed: 0.5348258706467662


k: 2
Accuracy would be: 0.5225
Precision obtained: 0.5178217821782178
Recall is: 0.65375
F Measure observed: 0.5779005524861879


k: 3
Accuracy would be: 0.5229166666666667
Precision obtained: 0.5193253689388616
Recall is: 0.6158333333333333
F Measure observed: 0.5634769348074724


k: 4
Accuracy would be: 0.5215625
Precision obtained: 0.5173978819969742
Recall is: 0.64125
F Measure observed: 0.5727044376221043


k: 5
Accuracy would be: 0.52575
Precision obtained: 0.5213781652137817
Recall is: 0.628
F Measure observed: 0.5697437060557949


k: 6
Accuracy would be: 0.526875
Precision obtained: 0.5217244863590434
Recall is: 0.6454166666666666
F Measure observed: 0.5770162041348482


k: 7
Accuracy would be: 0.5257142857142857
Precision obtained: 0.5211889346674514
Recall is: 0.6325
F Measure observed: 0.5714746692481446


k: 8
Accuracy would be: 0.5271875
Precisio

In [51]:
# test accuracy, precision, recall, and F-measure to get the ideal k
#The valid set suggests using 2 might be a good choice
tp = 0
tn = 0
fp = 0
fn = 0
total = 0
k=2


for row in test:
    total +=1
    x = np.array(row[:-1])
    true_val = row[-1]

    decision = class_map(x,k)

    if decision == 0:
        if true_val == 0: #specificity
            tn+=1
        else: #Error Type II
            fn+=1
    else:
        if true_val == 0: #Error Type I
            fp+=1
        else: #sensitivity
            tp+=1



acc = (tn+tp)/total
prec = tp/(tp+fp) 
rec = tp/(tp+fn)
f = 2*prec*rec/(prec+rec)

print(f"k: {k}")
print(f"Accuracy would be: {acc}")
print(f"Precision obtained: {prec}")
print(f"Recall is: {rec}")
print(f"F Measure observed: {f}")
print('\n')

k: 2
Accuracy would be: 0.56625
Precision obtained: 0.5459272097053726
Recall is: 0.7875
F Measure observed: 0.6448311156601843


